# Generated by Django 5.0.3 on 2024-03-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='institutionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.institute'),
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='policyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.policy'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('policyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.policy')),
            ],
        ),
    ]
