# Generated by Django 5.0.3 on 2024-03-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_institute_departmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='policyId',
        ),
    ]
