# Generated by Django 5.0.3 on 2024-04-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_firstname_user_lastname_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.institute'),
        ),
    ]
