# Generated by Django 5.0.3 on 2024-04-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_policy_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='institute',
        ),
    ]
