# Generated by Django 5.0.3 on 2024-05-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_policy_institute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
